### ISSUE TITLE
add link for Blissfest Facebook page

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissfestri.com#30]
## Summary
Need to update the link for the festival Facebook page on the site for initial launch.
https://www.facebook.com/blissfestri/

## Details
Currently being used here, so would just need this line updated for now
https://github.com/AnalogStudiosRI/www.blissfestri.com/blob/main/src/components/signup-form/signup-form.js#L55

**Comment by Arindam200** [comment]
Can I Work on this?

**Comment by thescientist13** [comment]
Hey @Arindam200 that would be very helpful, thank you!
