### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissfestri.com#56]
## Summary
Create an about page for the festival.
![Screen Shot 2023-04-30 at 7 23 42 PM](https://user-images.githubusercontent.com/895923/235380718-169d7023-6703-45a6-90b3-fdd74087d30c.png)

## Outstanding Items
> Work can get started without these, and @thescientist13 will provide
1. [ ] photos for photo gallery (these images should be added the EventBrite listing)
1. [x] what is Blissfest image 

## Details
1. [ ] Add to navigation
1. [ ] Image Carousel

**Comment by ThienBNguyen** [comment]
Hi Owen I am interested in this issue. can I work on it?

**Comment by thescientist13** [comment]
Hey @ThienBNguyen thanks for reaching out!  This page is still a little incomplete right now because I'm still waiting on a final design and thinking about how to do the image carousel, but if you want to start it off by doing the basic layout with placeholders for the text and image carousel, that would be great!  I think on mobile I would probably make the carousel stack above the text.

I haven't thought about how to actually implement the image carousel yet but once I get the images we can see where we are, or maybe just a single image, we shall see.

**Comment by ThienBNguyen** [comment]
Hi @thescientist13 I have been looking over the project. I am having trouble starting the project. I am running into this "Error: Failed to find './theme.css'". after I cloned the project I ran command npm ci in the project folder and run npm run dev. I use localhost:1984 to run on chrome browser which as the terminal display "Started local development server at localhost:1984". I use command "npm run serve" give an error of "Could not resolve entry module".  my node version is v18.10.0.

**Comment by thescientist13** [comment]
Hey sorry to hear you're running into issues with the project @ThienBNguyen !

Can you share some screenshots of what you are seeing?  Are these errors you are getting from the browser console or the terminal?  Are you trying to add any new pages or just running what is in the repo currently?  Also, what operating system are you on?

if you don't mind, when replying, depending on what you feel most comfortable with, could you either:
- Create a [_Q & A_ discsison](https://github.com/AnalogStudiosRI/www.blissfestri.com/discussions/new/choose)
- I have a Slack workspace you are free to join and we can work out any setup issues there if you like (in the **#blissfests-dev** channel

Thanks and happy to help you get up running!

**Comment by ThienBNguyen** [comment]
![Screenshot 2023-05-29 at 10 15 58 AM](https://github.com/AnalogStudiosRI/www.blissfestri.com/assets/48506100/2c692f06-7ca4-43cd-ac9b-bb409efb3478)
here is the error when I ran localhost:1984. can you help me resolve the issue? i can fix the readme after.

**Comment by thescientist13** [comment]
Hey @ThienBNguyen sorry for the  delay in responding here.

That all seems like it should be working.  Can you confirm what operating system you are using?  I can see if I can reproduce on my end.

**Comment by ThienBNguyen** [comment]
I am using macos.

**Comment by thescientist13** [comment]
Thanks for that info @ThienBNguyen and I use Mac as well but don't seem to have that issue.  I did some searching and perhaps this is the issue impacting you? - https://github.com/gohugoio/hugo/issues/7333

I wonder if you could try cloning / running the project from a a directory without spaces in it?  Maybe just try something simple like _/Users/thiennguyen/greenwood_ just as a quick test?
