### ISSUE TITLE
refactor header background image inline `style` to use Tailwind classes

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissfestri.com#61]
## Summary
The header component currently uses a `style` attribute for the background image
https://github.com/AnalogStudiosRI/www.blissfestri.com/blob/main/src/components/header/header.js
```html
<header
  class="pb-16 bg-repeat-x bg-bottom"
  style="background-image: url('/assets/images/tear-strip.webp');"
>
```

## Details
Would be good to get these styles into the `class` attribute to stay consistent with Tailwind usage.  Not sure if this is possible with v2, so should confirm that first.  I can help upgrade to v3 if needed.

**Comment by Sky-De** [comment]
hi there 
pls assign this to me 
i will fix it as soon as i get assignment
tahnks

**Comment by thescientist13** [comment]
Thanks for the offer @Sky-De !  I have now assigned the issue to you.  👍
